Planning to move iptables libexec detection to configure.
Signed-off-by: Jesper Dangaard Brouer <hawk@comx.dk>

diff --git a/iptables-module/Makefile.in b/iptables-module/Makefile.in
--- a/iptables-module/Makefile.in
+++ b/iptables-module/Makefile.in
@@ -13,6 +13,9 @@ version     = @PACKAGE_VERSION@
 # (Note the version comes from configure.ac AC_INIT)
 prefix      = @prefix@
 exec_prefix = @exec_prefix@
+libexecdir  = @libexecdir@
+#
+#configure_xtlibdir = @xtlibdir@
 
 # Targets
 # -------
@@ -65,6 +68,8 @@ iptables_bin = $(shell which iptables)
 iptables_version = $(shell ($(iptables_bin) -V | awk {'print $$2'} | cut -c 2-))
 IPT_FLAGS = -DIPTABLES_VERSION=\"$(iptables_version)\"
 
+# FIXME: Move below auto detecting xtlibdir to configure script
+#
 # Problem statement:
 #
 #  The userspace lib dir is differs on different Linux distributions,
@@ -109,7 +114,8 @@ lib_install: lib
 	@if test -d $(xtlibdir); then \
 	    $(CP) $(LIB_TARGETS) $(xtlibdir); \
 	else \
-	    echo "***ERROR*** - cannot find libexec install dir"; \
+	    echo "***ERROR*** - cannot find libexec (xtlibdir) install dir"; \
+	    exit 2; \
 	fi
 
 install: lib_install modules_install
